### ISSUE TITLE
Mixpanel: Add more page tracking

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#273]
# Background
https://www.notion.so/volumefi/EPIC-07-01-Mixpanel-Marketing-Metrics-Tracking-c412ecca42504f49b9daffef99c0206b

# Done when

- [ ] Kallisto blog and events pages are tracked
- [ ] Paloma blog and events pages are tracked
- [ ] Volume pages are tracked
