### ISSUE TITLE
Mixpanel: Event registration tracking

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#274]
### Background
https://www.notion.so/volumefi/EPIC-07-01-Mixpanel-Marketing-Metrics-Tracking-c412ecca42504f49b9daffef99c0206b

### Done when

- [x] Event clicks for Kallisto are tracked
- [x] Event clicks for Paloma are tracked
- [x] Event clicks for Volume are tracked
