### ISSUE TITLE
Mixpanel tracking

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#472]
Background: 
https://www.notion.so/volumefi/EPIC-09-16-Paloma-tracking-for-public-launch-f02f706b8b8446058a45e7bc35010e1c

Done when

- [x] paloma-docs pages are tracked in Mixpanel as PAGE_LOAD events
- [x] internal traffic on paloma-docs is filtered out
- [x] button clicks on the palomachain.com landing page are tracked in mixpanel
- [x] total messages sent from (https://github.com/palomachain/message-fetcher) is sent to mixpanel

**Comment by rootedbox** [comment]
@verabehr Mixpanel is now working. I need access to the palomachain.github.io repo whoever set that up. I also need to know what server is building the website.
